/**
 * AUDIT CAKUPAN (coverage audit) — `npm run audit:coverage`
 *
 * Membandingkan inventaris modul yang diamati pada situs acuan publik
 * (klinea.id/app.html — nama modul & alat saja, bukan konten) terhadap
 * implementasi lokal. Laporan dihasilkan lewat console; kegagalan hanya
 * bila item prioritas wajib (must-have) tidak ditemukan.
 */
import { describe, expect, test } from "vitest";
import { SCORES } from "@/lib/data/scores";
import { CALCULATORS } from "@/lib/data/calculators";
import { DRUGS } from "@/lib/data/drugs";
import { drugInteractions } from "@/lib/data/interactions";
import { procedureEntries } from "@/lib/data/indications";
import { guidelines } from "@/lib/data/guidelines";
import { icd10Codes } from "@/lib/data/icd10";
import { globalSearch } from "@/lib/search";
import canonical from "@/lib/generated/klinea-content.json";

/* ------------------------------------------------------------------ */
/* Inventaris modul pada situs acuan (hasil audit publik)              */
/* ------------------------------------------------------------------ */
const REFERENCE_MODULES: Record<string, { observed: number; note: string }> = {
  "Skrining & Skor (TOOLS)": { observed: 132, note: "meta id/sp/name yang teramati pada data publik" },
  "Kalkulator Klinis (CALCS)": { observed: 12, note: "modul kalkulator inti pada app publik" },
  "Dosis Obat (DRUGS)": { observed: 452, note: "jumlah entri id obat pada data publik (termasuk bentuk sediaan/indikasi ganda)" },
  "Interaksi Obat (DRUG_IX)": { observed: 100, note: "perkiraan pasangan interaksi pada data publik" },
  "Panduan Klinis (GUIDELINES)": { observed: 340, note: "entri panduan pada data publik" },
  "Kamus ICD-10": { observed: 1893, note: "perkiraan entri ICD-10 publik (subset berbahasa Indonesia)" },
  "Bahan Pangan (FOODS)": { observed: 303, note: "entri bahan pangan publik" },
};

/* Item prioritas pada situs acuan → kandidat slug lokal (periksa keberadaan) */
const PRIORITY_SCORES: { ref: string; local: string[] }[] = [
  { ref: "qSOFA", local: ["qsofa"] },
  { ref: "SOFA", local: ["sofa"] },
  { ref: "SIRS", local: ["sirs"] },
  { ref: "NEWS2", local: ["news2"] },
  { ref: "MEWS", local: ["mews"] },
  { ref: "GCS", local: ["gcs"] },
  { ref: "CURB-65", local: ["curb65"] },
  { ref: "PSI/PORT", local: ["psi"] },
  { ref: "Wells PE", local: ["wells-pe"] },
  { ref: "Wells DVT", local: ["wells-dvt"] },
  { ref: "PERC", local: ["perc"] },
  { ref: "HEART", local: ["heart"] },
  { ref: "TIMI NSTEMI", local: ["timi"] },
  { ref: "Glasgow-Blatchford", local: ["blatchford"] },
  { ref: "Ranson", local: ["ranson"] },
  { ref: "Alvarado", local: ["alvarado"] },
  { ref: "Centor/McIsaac", local: ["centor"] },
  { ref: "APGAR", local: ["apgar"] },
  { ref: "Downes", local: ["downes"] },
  { ref: "Silverman-Anderson", local: ["silverman"] },
  { ref: "Sarnat (HIE)", local: ["sarnat"] },
  { ref: "AKI KDIGO", local: ["kdigo-aki"] },
  { ref: "CKD staging", local: ["ckd-stage"] },
  { ref: "DKA/HHS", local: ["dka", "hhs"] },
  { ref: "Preeklampsia", local: ["preeclampsia"] },
  { ref: "HELLP", local: ["hellp"] },
  { ref: "CHA2DS2-VASc", local: ["chadsvasc"] },
  { ref: "HAS-BLED", local: ["hasbled"] },
  { ref: "Canadian CT Head Rule", local: ["canadian-ct-head"] },
  { ref: "ICH Score", local: ["ich-score"] },
  { ref: "Hunt-Hess", local: ["hunt-hess"] },
  { ref: "ABCD2", local: ["abcd2"] },
  { ref: "FOUR Score", local: ["four"] },
  { ref: "NIHSS", local: ["nihss"] },
  { ref: "MTBS/IMCI (batuk-napas)", local: ["imci-batuk"] },
  { ref: "WHO Severe Acute Malnutrition", local: ["who-sam"] },
  { ref: "Kawasaki", local: ["kawasaki"] },
  { ref: "Jones (Demam Rematik)", local: ["jones"] },
  { ref: "DIC ISTH", local: ["dic-isth"] },
  { ref: "CAM (Delirium)", local: ["cam-delirium"] },
  { ref: "RASS", local: ["rass"] },
  { ref: "Child-Pugh", local: ["child-pugh"] },
  { ref: "Rockall", local: ["rockall"] },
  { ref: "Maddrey DF", local: ["maddrey"] },
  { ref: "TWIST", local: ["twist"] },
  { ref: "STOP-BANG", local: ["stopbang"] },
  { ref: "Amsel (BV)", local: ["amsel"] },
  { ref: "ECOG", local: ["ecog"] },
  { ref: "FRAIL", local: ["frail"] },
  { ref: "Katz ADL", local: ["katz"] },
  { ref: "ASA PS", local: ["asa"] },
  { ref: "Mallampati", local: ["mallampati"] },
  { ref: "Ottawa Ankle Rules", local: ["ottawa-ankle"] },
  { ref: "Gustilo-Anderson", local: ["gustilo"] },
  { ref: "Salter-Harris", local: ["salter-harris"] },
  { ref: "House-Brackmann", local: ["house-brackmann"] },
  { ref: "mMRC", local: ["mmrc"] },
  { ref: "Osteoporosis WHO T-score", local: ["osteoporosis-tscore"] },
  { ref: "IPSS", local: ["ipss"] },
  { ref: "Wagner (ulkus diabetik)", local: ["wagner"] },
  { ref: "Revised Trauma Score", local: ["rts"] },
  { ref: "GINA Control Asma", local: ["gina-control"] },
  { ref: "Lawton IADL", local: ["lawton"] },
  { ref: "Palliative Performance Scale", local: ["pps"] },
  { ref: "Hinchey (Divertikulitis)", local: ["hinchey"] },
  { ref: "Epworth Sleepiness Scale", local: ["epworth"] },
  { ref: "Glasgow-Blatchford", local: ["glasgow-blatchford"] },
  { ref: "PHQ-9", local: ["phq9"] },
  { ref: "GAD-7", local: ["gad7"] },
  { ref: "CAGE (Alkohol)", local: ["cage"] },
  { ref: "Morse Fall Scale", local: ["morse-fall"] },
  { ref: "Braden (Luka Tekan)", local: ["braden"] },
  { ref: "ASIA Impairment Scale", local: ["asia-impairment"] },
  { ref: "Fisher (SAH)", local: ["fisher-sah"] },
  { ref: "WFNS (SAH)", local: ["wfns"] },
  { ref: "sPESI (Emboli Paru)", local: ["sspesi"] },
  { ref: "Padua (Risiko VTE)", local: ["padua"] },
  { ref: "Geneva Revisi (PE)", local: ["geneva-pe"] },
  { ref: "Klasifikasi ACS (STEMI vs NSTEMI)", local: ["acs-stemi-vs-nstemi"] },
  { ref: "ASPECTS (CT Stroke)", local: ["aspects-ct"] },
  { ref: "Kelayakan Trombolisis IV (rtPA)", local: ["trombolisis-iv"] },
  { ref: "Framingham (Gagal Jantung)", local: ["framingham-hf"] },
  { ref: "CIWA-Ar (Putus Alkohol)", local: ["ciwa-ar"] },
  { ref: "Burch-Wartofsky (Badai Tiroid)", local: ["burch-wartofsky"] },
  { ref: "GRACE (ACS)", local: ["grace"] },
  { ref: "PESI (Emboli Paru)", local: ["pesi"] },
  { ref: "Kriteria ICU Pneumonia (IDSA/ATS)", local: ["icu-pneumonia"] },
  { ref: "Kontraindikasi Nitrat", local: ["kontra-nitrat"] },
  { ref: "Kontraindikasi Beta-blocker", local: ["kontra-bb"] },
  { ref: "Kontraindikasi Fibrinolitik", local: ["kontra-fibrinolitik"] },
  { ref: "Kontraindikasi Metformin", local: ["kontra-metformin"] },
  { ref: "Kontraindikasi ACEi/ARB", local: ["kontra-acei"] },
  { ref: "Kontraindikasi Adenosin", local: ["kontra-adenosin"] },
  { ref: "Kontraindikasi Heparin & HIT", local: ["kontra-heparin"] },
  { ref: "Risiko Nefropati Kontras", local: ["kontra-kontras"] },
  { ref: "Kontraindikasi Pungsi Lumbal", local: ["kontra-lp"] },
  { ref: "Indikasi Intubasi", local: ["indikasi-intubasi"] },
  { ref: "Indikasi & Kontraindikasi NIV", local: ["indikasi-niv"] },
  { ref: "Indikasi Terapi Oksigen", local: ["indikasi-o2"] },
  { ref: "Indikasi Steroid Respirasi", local: ["indikasi-steroid-resp"] },
  { ref: "Indikasi Kardioversi Elektrik", local: ["indikasi-kardioversi"] },
  { ref: "Indikasi Pacu Jantung Sementara", local: ["indikasi-pacu"] },
  { ref: "Indikasi Trombektomi Mekanik", local: ["indikasi-trombektomi"] },
  { ref: "Indikasi Trombolisis PE", local: ["indikasi-trombolisis-pe"] },
  { ref: "Kontraindikasi Antikoagulan", local: ["indikasi-antikoagulan"] },
  { ref: "Indikasi Transfusi PRC", local: ["indikasi-transfusi-prc"] },
  { ref: "Indikasi Transfusi Trombosit", local: ["indikasi-transfusi-plt"] },
  { ref: "Indikasi Transfusi FFP", local: ["indikasi-ffp"] },
  { ref: "Indikasi Dialisis pada Keracunan", local: ["indikasi-extrip"] },
  { ref: "Indikasi Apendektomi", local: ["indikasi-apendektomi"] },
  { ref: "Indikasi MgSO4", local: ["indikasi-mgso4"] },
  { ref: "Indikasi Nalokson", local: ["indikasi-nalokson"] },
  { ref: "Indikasi Hemodialisis Akut (AEIOU)", local: ["indikasi-hd"] },
  { ref: "Kriteria Migrain ICHD-3", local: ["migrain-ichd3"] },
  { ref: "Kriteria Tension-Type Headache", local: ["tension-headache"] },
  { ref: "Kriteria Cluster Headache", local: ["cluster-headache"] },
  { ref: "Status Epileptikus", local: ["status-epileptikus"] },
  { ref: "CAM-ICU", local: ["cam-icu"] },
  { ref: "Kriteria Depresi Mayor DSM-5", local: ["depresi-mayor"] },
  { ref: "Kriteria GAD DSM-5", local: ["gad-dsm5"] },
  { ref: "Kriteria Panik DSM-5", local: ["panic-dsm5"] },
  { ref: "KPSP (Kemenkes)", local: ["kpsp"] },
  { ref: "M-CHAT-R (Autisme)", local: ["mchat-r"] },
  { ref: "Denver II", local: ["denver2"] },
  { ref: "SLEDAI-2K (Lupus)", local: ["sledai-2k"] },
  { ref: "DAS28-CRP (RA)", local: ["das28-crp"] },
  { ref: "Gout ACR/EULAR 2015", local: ["gout-acr"] },
  { ref: "Derajat Anafilaksis (Ring-Messmer)", local: ["anafilaksis-grade"] },
  { ref: "RMI (Tumor Ovarium)", local: ["rmi-ovarium"] },
  { ref: "RECIST 1.1", local: ["recist"] },
  { ref: "Karnofsky", local: ["karnofsky"] },
  { ref: "Clinical Frailty Scale", local: ["clinical-frailty-scale"] },
  { ref: "SKILAS (Lansia)", local: ["skilas"] },
  { ref: "ESAS (Paliatif)", local: ["esas"] },
  { ref: "Tokyo (Kolesistitis)", local: ["tokyo-kolesistitis"] },
  { ref: "Sudut Cobb (Skoliosis)", local: ["cobb-angle"] },
  { ref: "Garden (Collum Femoris)", local: ["garden-fraktur"] },
  { ref: "Sindrom Kompartemen (6P)", local: ["kompartemen-6p"] },
  { ref: "RA ACR/EULAR 2010", local: ["ra-acr-eular"] },
  { ref: "Hanifin-Rajka (Dermatitis Atopik)", local: ["hanifin-rajka"] },
  { ref: "SCORTEN (SJS/TEN)", local: ["scorten"] },
  { ref: "Hurley (Hidradenitis)", local: ["hurley"] },
  { ref: "Urtikaria (Klasifikasi)", local: ["urtikaria-akut"] },
  { ref: "OMA (Kriteria)", local: ["otoskopi-oma"] },
  { ref: "Rinosinusitis Akut", local: ["rinosinusitis-akut"] },
  { ref: "Abses Peritonsil", local: ["abses-peritonsil"] },
  { ref: "Vertigo Perifer vs Sentral", local: ["vertigo-diff"] },
  { ref: "Tersangka Glaukoma", local: ["glaukoma-suspek"] },
  { ref: "Glaukoma Sudut Tertutup Akut", local: ["glaukoma-akut"] },
  { ref: "Ulkus Kornea (Red Flag)", local: ["ulkus-kornea"] },
  { ref: "Ablasio Retina (Red Flag)", local: ["ablasio-retina"] },
  { ref: "Retinopati Diabetik (Stadium)", local: ["retinopati-diabetik"] },
  { ref: "AMD (Klasifikasi)", local: ["amd-klasifikasi"] },
  { ref: "IIEF-5 (Disfungsi Ereksi)", local: ["iief5"] },
  { ref: "Retensi Urin Akut", local: ["aur-retensi-urin"] },
  { ref: "Overactive Bladder", local: ["oab"] },
  { ref: "Kolik Renal", local: ["renal-colic"] },
  { ref: "AKI Postrenal", local: ["aki-postrenal"] },
  { ref: "Klasifikasi ISK", local: ["klasifikasi-isk"] },
  { ref: "WIfI (SVS)", local: ["wifi-svs"] },
  { ref: "Kualifikasi Derajat Luka (KUHP)", local: ["derajat-luka"] },
  { ref: "Estimasi Saat Kematian", local: ["saat-kematian"] },
  { ref: "Uji Apung Paru", local: ["uji-apung-paru"] },
];

const PRIORITY_GUIDELINES: { ref: string; local: string }[] = [
  { ref: "Cedera Kepala", local: "cedera-kepala" },
  { ref: "Trauma Toraks", local: "trauma-toraks" },
  { ref: "Luka Bakar", local: "luka-bakar" },
  { ref: "Hipertensi Krisis", local: "hipertensi-krisis" },
  { ref: "Stroke Hemoragik (ICH)", local: "stroke-hemoragik" },
  { ref: "Meningitis", local: "meningitis" },
  { ref: "Kejang Demam", local: "kejang-demam" },
  { ref: "Demam Tifoid", local: "demam-tifoid" },
  { ref: "Malaria", local: "malaria" },
  { ref: "Tetanus", local: "tetanus" },
  { ref: "Sirosis & Komplikasi", local: "sirosis" },
  { ref: "Perdarahan SCBA (UGIB)", local: "ugib" },
  { ref: "Hiperkalemia", local: "hiperkalemia" },
  { ref: "Sepsis Neonatorum", local: "sepsis-neonatorum" },
  { ref: "Ikterus Neonatorum", local: "ikterus-neonatorum" },
  { ref: "Perdarahan Pascapersalinan", local: "pph" },
  { ref: "Keracunan Organofosfat", local: "keracunan-organofosfat" },
  { ref: "Overdosis Parasetamol", local: "overdosis-parasetamol" },
  { ref: "Glaukoma Akut", local: "glaukoma-akut" },
  { ref: "DVT & Emboli Paru", local: "dvt-pe" },
  { ref: "Diabetes Gestasional", local: "diabetes-gestasional" },
  { ref: "Status Epileptikus", local: "status-epileptikus" },
  { ref: "Ensefalitis", local: "ensefalitis" },
  { ref: "Leptospirosis", local: "leptospirosis" },
  { ref: "Rabies", local: "rabies" },
  { ref: "Gigitan Ular Berbisa", local: "gigitan-ular" },
  { ref: "Anafilaksis", local: "anafilaksis" },
  { ref: "Hipoglikemia", local: "hipoglikemia" },
  { ref: "Asfiksia Neonatorum", local: "asfiksia-neonatorum" },
  { ref: "Kehamilan Ektopik Terganggu", local: "kehamilan-ektopik" },
  { ref: "Bronkiolitis", local: "bronkiolitis" },
  { ref: "Epistaksis", local: "epistaksis" },
  { ref: "Kolik Renal", local: "kolik-renal" },
  { ref: "Sindrom Kompartemen", local: "sindrom-kompartemen" },
  { ref: "Anemia Defisiensi Besi", local: "anemia-defisiensi-besi" },
  { ref: "Selulitis & Erisipelas", local: "selulitis" },
  { ref: "Abdomen Akut", local: "abdomen-akut" },
  { ref: "OMA", local: "otitis-media-akut" },
  { ref: "Tonsilitis/Faringitis", local: "tonsilitis" },
  { ref: "Vertigo/BPPV", local: "vertigo-bppv" },
  { ref: "Bell's Palsy", local: "bells-palsy" },
  { ref: "Konjungtivitis", local: "konjungtivitis" },
  { ref: "Dermatitis Atopik", local: "dermatitis-atopik" },
  { ref: "Skabies", local: "skabies" },
  { ref: "Herpes Zoster", local: "herpes-zoster" },
  { ref: "Depresi Mayor", local: "depresi" },
  { ref: "Gangguan Cemas", local: "ansietas" },
  { ref: "Hemoroid", local: "hemoroid" },
  { ref: "BPH/LUTS", local: "bph-luts" },
  { ref: "ISK Dewasa", local: "uti" },
  { ref: "Fibrilasi Atrium", local: "atrial-fibrilasi" },
  { ref: "Atrial Flutter", local: "atrial-flutter" },
  { ref: "SVT", local: "svt" },
  { ref: "VT & VF", local: "vt-vf" },
  { ref: "Blok AV", local: "av-block" },
  { ref: "Perikarditis Akut", local: "perikarditis-akut" },
  { ref: "Endokarditis Infektif", local: "endokarditis-infektif" },
  { ref: "Syok Kardiogenik", local: "syok-kardiogenik" },
  { ref: "Miokarditis", local: "miokarditis" },
  { ref: "Diseksi Aorta", local: "diseksi-aorta" },
  { ref: "Hipertiroid & Krisis Tiroid", local: "hipertiroid" },
  { ref: "Hipotiroid & Koma Miksedema", local: "hipotiroid" },
  { ref: "Prediabetes", local: "prediabetes" },
  { ref: "DM Tipe 1", local: "dm-tipe-1" },
  { ref: "SIADH", local: "siadh" },
  { ref: "Diabetes Insipidus", local: "diabetes-insipidus" },
  { ref: "Insufisiensi Adrenal & Krisis", local: "insufisiensi-adrenal" },
  { ref: "Dislipidemia", local: "dislipidemia" },
  { ref: "Hipokalemia", local: "hipokalemia" },
  { ref: "Nefritis Lupus", local: "nefritis-lupus" },
  { ref: "TIA", local: "tia" },
  { ref: "Demensia", local: "demensia" },
  { ref: "HAP/VAP", local: "hap-vap" },
  { ref: "ARDS", local: "ards" },
  { ref: "COVID-19", local: "covid19" },
  { ref: "Influenza", local: "influenza" },
  { ref: "Bronkitis Akut", local: "bronkitis-akut" },
  { ref: "ISPA / Common Cold", local: "ispa-common-cold" },
  { ref: "Parotitis (Mumps)", local: "parotitis-mumps" },
  { ref: "Chikungunya", local: "chikungunya" },
  { ref: "Filariasis", local: "filariasis" },
  { ref: "Kecacingan (STH)", local: "kecacingan-sth" },
  { ref: "TB Milier", local: "tb-milier" },
  { ref: "Hepatitis A", local: "hepatitis-a" },
  { ref: "Disentri", local: "disentri" },
  { ref: "Konstipasi", local: "konstipasi" },
  { ref: "IBS", local: "ibs" },
  { ref: "Akalasia", local: "akalasia" },
  { ref: "Divertikulitis Akut", local: "divertikulitis-akut" },
  { ref: "Pankreatitis Kronik", local: "pankreatitis-kronik" },
  { ref: "Talasemia", local: "talasemia" },
  { ref: "Hemofilia", local: "hemofilia" },
  { ref: "AIHA", local: "aiha" },
  { ref: "Mieloma Multipel", local: "mieloma-multipel" },
  { ref: "Difteri", local: "difteri" },
  { ref: "Pertusis", local: "pertusis" },
  { ref: "Campak", local: "campak" },
  { ref: "Varisela", local: "varisela" },
  { ref: "Croup", local: "croup" },
  { ref: "ISK Anak", local: "isk-anak" },
  { ref: "Sindrom Nefrotik Anak", local: "nefrotik-anak" },
  { ref: "Demam Rematik Akut", local: "demam-rematik-akut" },
  { ref: "Ketuban Pecah Dini", local: "kpd" },
  { ref: "Plasenta Previa", local: "plasenta-previa" },
  { ref: "Solusio Plasenta", local: "solusio-plasenta" },
  { ref: "Abortus", local: "abortus" },
  { ref: "Hiperemesis Gravidarum", local: "hiperemesis-gravidarum" },
  { ref: "Mola Hidatidosa", local: "mola-hidatidosa" },
  { ref: "Persalinan Preterm", local: "persalinan-preterm" },
  { ref: "Otitis Eksterna", local: "otitis-eksterna" },
  { ref: "OMSK", local: "omsk" },
  { ref: "Tuli Mendadak (SSNHL)", local: "tuli-mendadak" },
  { ref: "Rinitis Alergi", local: "rinitis-alergi" },
  { ref: "Katarak", local: "katarak" },
  { ref: "Uveitis Anterior", local: "uveitis" },
  { ref: "Selulitis Orbita", local: "selulitis-orbita" },
  { ref: "Skizofrenia", local: "skizofrenia" },
  { ref: "Gangguan Bipolar", local: "bipolar" },
  { ref: "Insomnia", local: "insomnia" },
  { ref: "ADHD", local: "adhd" },
  { ref: "Karies Gigi", local: "karies-gigi" },
  { ref: "Stomatitis Aftosa", local: "stomatitis-aftosa" },
  { ref: "Carpal Tunnel Syndrome", local: "carpal-tunnel" },
  { ref: "Plantar Fasciitis", local: "plantar-fasciitis" },
  { ref: "Frozen Shoulder", local: "frozen-shoulder" },
  // batch J–R (perluasan 163 → 340 panduan)
  { ref: "GERD", local: "gerd" },
  { ref: "Dispepsia", local: "dispepsia" },
  { ref: "Tukak Peptik (PUD)", local: "pud" },
  { ref: "Perdarahan SCBA (LGIB)", local: "lgib" },
  { ref: "Kolesistitis Akut", local: "kolesistitis-akut" },
  { ref: "Kolangitis Akut", local: "kolangitis-akut" },
  { ref: "Apendisitis Akut", local: "apendisitis-akut" },
  { ref: "Ileus Obstruktif", local: "ileus-obstruktif" },
  { ref: "Hernia", local: "hernia" },
  { ref: "Peritonitis", local: "peritonitis" },
  { ref: "Fisura Ani", local: "fisura-ani" },
  { ref: "Abses & Fistula Perianal", local: "fistula-perianal" },
  { ref: "Lipoma", local: "lipoma" },
  { ref: "Kista Epidermoid", local: "kista-epidermoid" },
  { ref: "Mastitis & Abses Payudara", local: "mastitis" },
  { ref: "Fibroadenoma Mammae", local: "fam" },
  { ref: "Dismenore", local: "dismenore" },
  { ref: "Kanker Payudara", local: "kanker-payudara" },
  { ref: "Kanker Serviks", local: "kanker-serviks" },
  { ref: "Karsinoma Nasofaring", local: "knf" },
  { ref: "Kanker Paru", local: "kanker-paru" },
  { ref: "Kanker Kolorektal", local: "kanker-kolorektal" },
  { ref: "HCC", local: "hcc" },
  { ref: "Kanker Prostat", local: "kanker-prostat" },
  { ref: "Limfoma", local: "limfoma" },
  { ref: "Leukemia Akut", local: "leukemia" },
  { ref: "Osteosarkoma", local: "osteosarkoma" },
  { ref: "Sarkoma Ewing", local: "sarkoma-ewing" },
  { ref: "GCT Tulang", local: "gct" },
  { ref: "Kondrosarkoma", local: "kondrosarkoma" },
  { ref: "Metastasis Tulang", local: "metastasis-tulang" },
  { ref: "Sarkoma Jaringan Lunak", local: "sarkoma-jaringan-lunak" },
  { ref: "Ulkus Dekubitus", local: "ulkus-dekubitus" },
  { ref: "PJB (Pendekatan)", local: "pjb-pendekatan" },
  { ref: "VSD", local: "vsd" },
  { ref: "ASD", local: "asd" },
  { ref: "PDA", local: "pda" },
  { ref: "Tetralogi Fallot", local: "tof" },
  { ref: "TGA", local: "tga" },
  { ref: "RDS Neonatus", local: "rds-neonatus" },
  { ref: "BBLR & Prematuritas", local: "bblr-prematur" },
  { ref: "Penyakit Kawasaki", local: "kawasaki" },
  { ref: "ITP", local: "itp" },
  { ref: "SJS/TEN", local: "sjs-ten" },
  { ref: "Migrain", local: "migrain" },
  { ref: "Cluster Headache", local: "cluster-headache" },
  { ref: "Tension-Type Headache", local: "tth" },
  { ref: "Epilepsi", local: "epilepsi" },
  { ref: "Penyakit Parkinson", local: "parkinson" },
  { ref: "Neuralgia Trigeminal", local: "neuralgia-trigeminal" },
  { ref: "Neuropati Perifer", local: "neuropati-perifer" },
  { ref: "Delirium", local: "delirium" },
  { ref: "PTSD", local: "ptsd" },
  { ref: "OCD", local: "ocd" },
  { ref: "Gangguan Alkohol & Putus Alkohol", local: "gangguan-alkohol" },
  { ref: "Gangguan Skizoafektif", local: "skizoafektif" },
  { ref: "Gangguan Opioid", local: "gangguan-opioid" },
  { ref: "KDRT", local: "kdrt" },
  { ref: "Kusta", local: "kusta" },
  { ref: "Frambusia", local: "frambusia" },
  { ref: "Tinea", local: "tinea" },
  { ref: "Kandidiasis Kutis", local: "kandidiasis-kutis" },
  { ref: "Akne Vulgaris", local: "akne-vulgaris" },
  { ref: "Impetigo", local: "impetigo" },
  { ref: "Folikulitis/Furunkel", local: "folikulitis" },
  { ref: "Veruka", local: "veruka" },
  { ref: "Moluskum", local: "moluskum" },
  { ref: "Pedikulosis", local: "pedikulosis" },
  { ref: "Miliaria", local: "miliaria" },
  { ref: "Psoriasis", local: "psoriasis" },
  { ref: "Erupsi Obat", local: "erupsi-obat" },
  { ref: "Pitiriasis Versikolor", local: "pitiriasis-versikolor" },
  { ref: "Pitiriasis Alba", local: "pitiriasis-alba" },
  { ref: "Vitiligo", local: "vitiligo" },
  { ref: "Melasma", local: "melasma" },
  { ref: "Pemfigus Vulgaris", local: "pemfigus" },
  { ref: "Alopesia Areata", local: "alopesia-areata" },
  { ref: "Urtikaria & Angioedema", local: "urtikaria-angioedema" },
  { ref: "Dermatitis Kontak", local: "dermatitis-kontak" },
  { ref: "Duh Vagina", local: "duh-vagina" },
  { ref: "Vaginosis Bakterial", local: "bv" },
  { ref: "Kandidiasis Vulvovaginalis", local: "kvv" },
  { ref: "Trikomoniasis", local: "trikomoniasis" },
  { ref: "Servisitis (Gonore/Klamidia)", local: "servisitis" },
  { ref: "Gonore", local: "gonore" },
  { ref: "Klamidia", local: "klamidia" },
  { ref: "Sifilis", local: "sifilis" },
  { ref: "Kondiloma Akuminata", local: "kondiloma" },
  { ref: "Ulkus Mole (Chancroid)", local: "chancroid" },
  { ref: "PID", local: "pid" },
  { ref: "AUB", local: "aub" },
  { ref: "Mioma Uteri", local: "mioma" },
  { ref: "Endometriosis", local: "endometriosis" },
  { ref: "PCOS", local: "pcos" },
  { ref: "Retensi Urin Akut", local: "retensi-urin-akut" },
  { ref: "Torsio Testis", local: "torsio-testis" },
  { ref: "Pielonefritis Akut", local: "pielonefritis-akut" },
  { ref: "Striktur Uretra", local: "striktur-uretra" },
  { ref: "Fimosis", local: "fimosis" },
  { ref: "Parafimosis", local: "parafimosis" },
  { ref: "Epididimitis & Orkitis", local: "epididimitis-orkitis" },
  { ref: "Hidrokel", local: "hidrokel" },
  { ref: "Varikokel", local: "varikokel" },
  { ref: "Prostatitis", local: "prostatitis" },
  { ref: "Fraktur Terbuka", local: "fraktur-terbuka" },
  { ref: "Fraktur Tertutup", local: "fraktur-tertutup" },
  { ref: "Artritis Septik", local: "artritis-septik" },
  { ref: "Osteomielitis", local: "osteomielitis" },
  { ref: "Tenosinovitis De Quervain", local: "de-quervain" },
  { ref: "Trigger Finger", local: "trigger-finger" },
  { ref: "Epikondilitis Lateral", local: "epikondilitis" },
  { ref: "Sprain & Strain", local: "sprain-strain" },
  { ref: "Dislokasi Sendi", local: "dislokasi" },
  { ref: "Nyeri Punggung Bawah & HNP", local: "hnp" },
  { ref: "OSA", local: "osa" },
  { ref: "Blefaritis", local: "blefaritis" },
  { ref: "Pterigium", local: "pterigium" },
  { ref: "Perdarahan Subkonjungtiva", local: "perdarahan-subkonjungtiva" },
  { ref: "Ablasio Retina", local: "ablasio-retina" },
  { ref: "Keratitis / Ulkus Kornea", local: "keratitis-ulkus-kornea" },
  { ref: "Benda Asing & Trauma Kimia Mata", local: "benda-asing-mata" },
  { ref: "DIC", local: "dic" },
  { ref: "Tanatologi", local: "tanatologi" },
  { ref: "Traumatologi Forensik", local: "traumatologi" },
  { ref: "Kualifikasi Derajat Luka", local: "kualifikasi-luka" },
  { ref: "Visum et Repertum", local: "visum" },
  { ref: "Identifikasi Forensik (DVI)", local: "dvi" },
  { ref: "Forensik Kejahatan Seksual", local: "forensik-seksual" },
  { ref: "Lahir Hidup vs Lahir Mati", local: "lahir-hidup-mati" },
  { ref: "Toksikologi Forensik", local: "toksikologi-forensik" },
  { ref: "Gout", local: "gout" },
  { ref: "Osteoartritis", local: "osteoartritis" },
  { ref: "Artritis Reumatoid", local: "ra" },
  { ref: "Spondilitis Ankilosa", local: "spondilitis" },
  { ref: "Periodontitis", local: "periodontitis" },
  { ref: "Kandidiasis Oral", local: "kandidiasis-oral" },
  { ref: "Tinnitus", local: "tinnitus" },
  { ref: "Abses Leher Dalam", local: "abses-leher-dalam" },
  { ref: "Infeksi Oportunistik HIV", local: "hiv-oi" },
  { ref: "Efusi Pleura", local: "efusi-pleura" },
  { ref: "Pneumotoraks", local: "pneumotoraks" },
  { ref: "Hemoptisis", local: "hemoptisis" },
  { ref: "Rinosinusitis Akut", local: "rinosinusitis-akut" },
  { ref: "Laringitis Akut", local: "laringitis-akut" },
  { ref: "Mastoiditis Akut", local: "mastoiditis-akut" },
  { ref: "Benda Asing & Serumen", local: "benda-asing-tht" },
  { ref: "Abses Peritonsil", local: "abses-peritonsil" },
  { ref: "Hordeolum & Kalazion", local: "hordeolum-kalazion" },
  { ref: "Oklusi Retina Sentral", local: "oklusi-retina" },
  { ref: "Glaukoma Sudut Terbuka", local: "glaukoma-pog" },
  { ref: "Gizi Buruk (SAM)", local: "gizi-buruk" },
  { ref: "Obesitas & Sindrom Metabolik", local: "obesitas-metabolik" },
  { ref: "Asfiksia Mekanik Forensik", local: "asfiksia-forensik" },
  { ref: "Hiperkalsemia", local: "hiperkalsemia" },
  { ref: "Hipokalsemia", local: "hipokalsemia" },
  { ref: "Hipernatremia", local: "hipernatremia" },
  { ref: "Hipofosfatemia", local: "hipofosfatemia" },
  { ref: "Anemia Aplastik", local: "anemia-aplastik" },
  { ref: "Bronkiektasis", local: "bronkiektasis" },
  { ref: "Fibrosis Paru / ILD", local: "fibrosis-paru" },
  { ref: "Kor Pulmonale", local: "kor-pulmonale" },
  { ref: "Osteoporosis", local: "osteoporosis" },
  { ref: "Rakhitis", local: "rakhitis" },
  { ref: "Skoliosis", local: "skoliosis" },
  { ref: "Limfadenopati", local: "limfadenopati" },
  { ref: "Splenomegali", local: "splenomegali" },
  { ref: "Polisitemia", local: "polisitemia" },
  { ref: "Neutropenia & Demam Neutropenia", local: "neutropenia" },
  { ref: "Syok Hipovolemik", local: "syok-hipovolemik" },
  { ref: "Trauma Abdomen", local: "trauma-abdomen" },
  { ref: "Trauma Maksilofasial", local: "trauma-maksilofasial" },
  { ref: "Cedera Medula Spinalis", local: "cedera-medula-spinalis" },
  { ref: "Intususepsi", local: "intususepsi" },
  { ref: "Stenosis Pilorik", local: "stenosis-pilorik" },
  { ref: "Hidronefrosis", local: "hidronefrosis" },
  { ref: "Nefropati Diabetik", local: "nefropati-diabetik" },
  { ref: "Angina Stabil (PJK Kronik)", local: "angina-stabil" },
];

/* Obat inti yang wajib ada (umum di praktik Indonesia) */
const PRIORITY_DRUGS = [
  "paracetamol", "amoxicillin", "ceftriaxone", "metronidazole", "ciprofloxacin", "azithromycin",
  "salbutamol", "furosemide", "captopril", "amlodipine", "metformin", "insulin-regular",
  "heparin", "warfarin", "aspirin", "clopidogrel", "diazepam", "midazolam", "epinephrine",
  "ondansetron", "omeprazole", "tranexamic-acid", "magnesium-sulfate", "ketorolac", "diclofenac",
  "mefenamic-acid", "metoclopramide", "lorazepam", "fluoxetine", "sucralfate", "lactulose",
  "allopurinol", "colchicine", "losartan", "atorvastatin", "bisoprolol",
  "norepinephrine", "dopamine", "dobutamine", "propofol", "fentanyl", "rocuronium",
  "succinylcholine", "lidocaine", "mannitol", "acetylcysteine", "pralidoxime", "flumazenil",
  "thiamine", "calcium-gluconate", "diltiazem", "rivaroxaban", "ticagrelor", "alteplase",
  "primaquine", "quinine", "methyldopa", "propylthiouracil", "methimazole", "insulin-nph",
  "hydrochlorothiazide", "glucagon", "tenofovir", "lamivudine", "dolutegravir",
  "morfin", "tramadol", "metamizol", "ketoprofen", "naproksen", "oksikodon",
  "tapentadol", "venlafaksin", "mirtazapin", "bupropion", "lamotrigin", "topiramat",
  "okskarbazepin", "lakosamid", "klonazepam", "levodopa-karbidopa", "pramipeksol",
  "memantin", "metilfenidat", "nimodipin", "sotalol", "flekainid", "ivabradine",
  "prasugrel", "fondaparinuks", "ezetimibe", "fenofibrat", "rosuvastatin", "enalapril",
  "atenolol", "indapamid", "eplerenon", "mesalazin", "azatioprin", "sevelamer",
  "isotretinoin", "amfoterisin-b", "vorikonazol", "itrakonazol", "griseofulvin",
  "terbinafin", "kolistin", "tigesiklin", "ertapenem", "aztreonam", "streptomisin",
  "sofosbuvir-velpatasvir", "dietilkarbamazin", "mekobalamin", "sitikolin", "flunarizin",
  "prometazin", "racecadotril", "difenoksilat", "simetidin", "rifaximin", "peg",
  "fludrokortison", "gliklazid", "doksazosin", "kabergolin", "kolestiramin",
  "neostigmin", "sugammadeks", "bromheksin",
];

describe("audit cakupan terhadap situs acuan (coverage audit)", () => {
  const scoreIds = new Set(SCORES.map((s) => s.id));
  const guideIds = new Set(guidelines.map((g) => g.id));
  const drugIds = new Set(DRUGS.map((d) => d.id));

  test("laporan ringkasan modul", () => {
    const local: Record<string, number> = {
      "Skrining & Skor (TOOLS)": SCORES.length,
      "Kalkulator Klinis (CALCS)": CALCULATORS.length,
      "Dosis Obat (DRUGS)": DRUGS.length,
      "Interaksi Obat (DRUG_IX)": drugInteractions.length,
      "Panduan Klinis (GUIDELINES)": guidelines.length,
      "Kamus ICD-10": icd10Codes.length,
      "Indikasi & Kontraindikasi": procedureEntries.length,
    };
    const lines: string[] = [];
    lines.push("");
    lines.push("═══ AUDIT CAKUPAN (coverage) ═══");
    lines.push(`${"Modul".padEnd(38)} ${"Acuan".padStart(6)} ${"Lokal".padStart(6)}`);
    for (const [m, ref] of Object.entries(REFERENCE_MODULES)) {
      lines.push(`${m.padEnd(38)} ${String(ref.observed).padStart(6)} ${String(local[m] ?? 0).padStart(6)}`);
    }
    for (const [m, n] of Object.entries(local)) {
      if (!REFERENCE_MODULES[m]) lines.push(`${m.padEnd(38)} ${String("-").padStart(6)} ${String(n).padStart(6)}`);
    }
    console.log(lines.join("\n"));
    expect(true).toBe(true);
  });

  test("seluruh skor kanonik hadir", () => {
    const missing = canonical.tools.filter((item) => !scoreIds.has(item.id)).map((item) => item.name);
    expect(missing).toEqual([]);
  });

  test("seluruh panduan kanonik hadir", () => {
    const missing = canonical.guidelines.filter((item) => !guideIds.has(item.id)).map((item) => item.name);
    expect(missing).toEqual([]);
  });

  test("seluruh obat kanonik hadir", () => {
    const missing = canonical.drugs.filter((item) => !drugIds.has(item.id)).map((item) => item.nm);
    expect(missing).toEqual([]);
  });

  test("pencarian menemukan 'cedera kepala' (skor + panduan + ICD)", () => {
    const groups = globalSearch("cedera kepala", 10);
    const anyHit = groups.some((g) => g.hits.length > 0);
    const hitDescr = groups.map((g) => `${g.label}: ${g.hits.length}`).join(", ");
    console.log(`\nPencarian 'cedera kepala' → ${hitDescr || "tanpa hasil"}`);
    expect(anyHit).toBe(true);
    const guideHit = groups.some((g) => g.key === "guidelines" && g.hits.length > 0);
    expect(guideHit).toBe(true);
  });
});
