"use client";

import { useEffect, useState } from "react";
import { ChevronDown } from "lucide-react";
import { BackLink, EmptyState, FilterInput, PageHeader } from "@/components/shared";

interface Antidote { id:string; toxin:string; antidote:string; category:string; availability:string; indication:string; doses:string[]; alternative?:string; warnings?:string[]; source:string }
interface Drug { id:string; name:string; category:string; pregnancyRating:string; lactationRating:string; summary:string; pregnancyNote:string; lactationNote:string }

export default function ClinicalReferencePageClient({ mode }: { mode: "antidotes" | "pregnancy" }) {
  const [items, setItems] = useState<(Antidote|Drug)[]>([]), [query,setQuery]=useState(""), [open,setOpen]=useState<string|null>(null), [loading,setLoading]=useState(true);
  useEffect(() => { const timer=setTimeout(() => { fetch(`${mode==='antidotes'?'/api/antidotes':'/api/pregnancy-drugs'}?q=${encodeURIComponent(query)}`,{cache:'no-store'}).then(r=>r.json()).then((d:{items:(Antidote|Drug)[]})=>setItems(d.items)).finally(()=>setLoading(false)); },150); return ()=>clearTimeout(timer); },[mode,query]);
  const isAntidote=mode==='antidotes';
  return <div><BackLink href="/igd-toolkit" label="Kembali ke Toolkit IGD"/><PageHeader title={isAntidote?'Panduan Toksikologi & Antidot':'Obat pada Kehamilan & Menyusui'}/>
    {!isAntidote && <div className="mb-5 rounded-lg border border-amber-400/40 bg-amber-50 p-4 text-xs leading-5 text-amber-950 dark:bg-amber-950/20 dark:text-amber-100"><strong className="block font-bold">Catatan penting</strong>Kategori kehamilan historis harus dibaca bersama usia gestasi, indikasi, dosis, durasi, dan data terbaru. Jangan menghentikan obat penting secara mendadak.</div>}
    <FilterInput value={query} onChange={(v)=>{setLoading(true);setQuery(v);}} placeholder={isAntidote?'Cari racun, obat, atau antidot':'Cari nama atau kelompok obat'}/>
    {loading?<p className="text-sm text-[var(--muted)]">Memuat referensi...</p>:items.length===0?<EmptyState message="Referensi tidak ditemukan."/>:<div className="workspace-panel overflow-hidden">{items.map((raw)=>{const item=raw as Antidote & Drug; const id=item.id; const expanded=open===id; const title=isAntidote?item.toxin:item.name; return <article key={id} className="border-b border-[var(--line)] last:border-b-0"><button onClick={()=>setOpen(expanded?null:id)} className="focus-ring flex w-full items-center gap-3 px-4 py-4 text-left hover:bg-black/[0.025] dark:hover:bg-white/[0.025]"><span className="min-w-0 flex-1"><strong className="display-type block text-sm font-bold">{title}</strong><span className="mt-1 block text-xs text-[var(--muted)]">{isAntidote?item.antidote:item.category}</span></span>{isAntidote?<span className="hidden rounded bg-accent/10 px-2 py-1 text-[10px] font-bold text-accent-strong sm:block">{item.availability}</span>:<span className="flex gap-1"><b className="rounded bg-accent/10 px-2 py-1 text-[10px]">Hamil {item.pregnancyRating}</b><b className="rounded bg-accent/10 px-2 py-1 text-[10px]">ASI {item.lactationRating}</b></span>}<ChevronDown className={`h-4 w-4 text-[var(--muted)] transition-transform ${expanded?'rotate-180':''}`}/></button>{expanded&&(isAntidote?<AntidoteDetail item={item}/>:<DrugDetail item={item}/>)}</article>})}</div>}
  </div>;
}

function AntidoteDetail({item}:{item:Antidote}) { return <div className="grid gap-5 border-t border-[var(--line)] p-5 md:grid-cols-2"><section><h3 className="text-xs font-bold">Indikasi</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{item.indication}</p><h3 className="mt-5 text-xs font-bold">Dosis</h3><ul className="mt-2 space-y-2 text-sm leading-6 text-[var(--muted)]">{item.doses.map(x=><li key={x} className="relative pl-4 before:absolute before:left-0 before:content-['•']">{x}</li>)}</ul></section><section>{item.alternative&&<><h3 className="text-xs font-bold">Alternatif</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{item.alternative}</p></>}{item.warnings?.length?<><h3 className="mt-5 text-xs font-bold">Peringatan</h3><ul className="mt-2 space-y-2 text-sm leading-6 text-[var(--muted)]">{item.warnings.map(x=><li key={x} className="relative pl-4 before:absolute before:left-0 before:content-['•']">{x}</li>)}</ul></>:null}<p className="mt-5 text-[10px] text-[var(--muted)]">Sumber: {item.source}</p></section></div> }
function DrugDetail({item}:{item:Drug}) { return <div className="grid gap-5 border-t border-[var(--line)] p-5 md:grid-cols-2"><section><h3 className="text-xs font-bold">Kehamilan</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{item.pregnancyNote}</p></section><section><h3 className="text-xs font-bold">Menyusui</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{item.lactationNote}</p></section><p className="text-sm leading-6 text-[var(--muted)] md:col-span-2">{item.summary}</p></div> }
