"use client";

import { useMemo, useState } from "react";
import { BackLink, PageHeader, SectionBand } from "@/components/shared";
import { correctedCalcium, correctedSodium, freeWaterDeficit, magnesiumDeficitEstimate, potassiumDeficitEstimate, sodiumCorrectionLimit } from "@/lib/calc/electrolytes";

const field = "focus-ring mt-1 h-11 w-full rounded-lg border border-[var(--line)] bg-[var(--surface-raised)] px-3 text-sm outline-none";
type Mode = "sodium" | "calcium" | "water" | "potassium" | "magnesium";

export default function ElectrolyteCalculator() {
  const [mode, setMode] = useState<Mode>("sodium"), [a, setA] = useState(130), [b, setB] = useState(300), [sex, setSex] = useState<"male"|"female">("male"), [older, setOlder] = useState(false);
  const config = { sodium: ["Natrium terkoreksi", "Natrium terukur, mmol/L", "Glukosa, mg/dL"], calcium: ["Kalsium terkoreksi", "Kalsium total, mg/dL", "Albumin, g/dL"], water: ["Defisit air bebas", "Natrium, mmol/L", "Berat badan, kg"], potassium: ["Estimasi defisit kalium", "Kalium, mmol/L", ""], magnesium: ["Estimasi defisit magnesium", "Magnesium, mg/dL", "Berat badan, kg"] }[mode];
  const result = useMemo(() => { try { if (mode === "sodium") return `${correctedSodium(a,b)} mmol/L`; if (mode === "calcium") return `${correctedCalcium(a,b)} mg/dL`; if (mode === "water") return `${freeWaterDeficit({ sodium:a, weightKg:b, sex, olderAdult:older })} L`; if (mode === "potassium") { const x=potassiumDeficitEstimate(a); return `${x.minMmol} sampai ${x.maxMmol} mmol`; } return `${magnesiumDeficitEstimate(a,b)} mg`; } catch { return "Input tidak valid"; } }, [a,b,mode,older,sex]);
  const select = (next: Mode) => { setMode(next); const defaults: Record<Mode,[number,number]>={sodium:[130,300],calcium:[7.5,2.5],water:[155,60],potassium:[2.8,0],magnesium:[1.2,60]}; setA(defaults[next][0]); setB(defaults[next][1]); };
  return <div><BackLink href="/igd-toolkit" label="Kembali ke Toolkit IGD" /><PageHeader title="Kalkulator Koreksi Elektrolit" />
    <div className="mb-4 flex flex-wrap gap-2">{([['sodium','Natrium'],['calcium','Kalsium'],['water','Air bebas'],['potassium','Kalium'],['magnesium','Magnesium']] as [Mode,string][]).map(([id,label]) => <button key={id} onClick={() => select(id)} data-active={mode===id} className="focus-ring rounded-full border border-[var(--line)] px-3 py-1.5 text-xs font-bold data-[active=true]:border-accent data-[active=true]:bg-accent/10 data-[active=true]:text-accent-strong">{label}</button>)}</div>
    <div className="grid gap-5 lg:grid-cols-2"><section className="workspace-panel overflow-hidden"><SectionBand>Parameter</SectionBand><div className="grid gap-4 p-5 sm:grid-cols-2"><label className="text-xs font-bold">{config[1]}<input type="number" step="0.1" value={a} onChange={(e)=>setA(Number(e.target.value))} className={field}/></label>{config[2] && <label className="text-xs font-bold">{config[2]}<input type="number" step="0.1" value={b} onChange={(e)=>setB(Number(e.target.value))} className={field}/></label>}{mode==='water' && <><label className="text-xs font-bold">Jenis kelamin<select value={sex} onChange={(e)=>setSex(e.target.value as typeof sex)} className={field}><option value="male">Laki-laki</option><option value="female">Perempuan</option></select></label><label className="flex items-center gap-3 self-end rounded-lg border border-[var(--line)] p-3 text-xs font-bold"><input type="checkbox" checked={older} onChange={(e)=>setOlder(e.target.checked)}/> Usia lanjut</label></>}</div></section>
    <section className="workspace-panel overflow-hidden"><SectionBand>{config[0]}</SectionBand><div className="p-5"><strong className="display-type text-3xl font-bold tabular-nums">{result}</strong><h3 className="mt-6 text-sm font-bold">Batas keselamatan</h3><p className="mt-2 text-xs leading-5 text-[var(--muted)]">{mode==='sodium'||mode==='water' ? sodiumCorrectionLimit(false) : "Sesuaikan terapi dengan gejala, fungsi ginjal, EKG, dan pemeriksaan serial. Estimasi bukan perintah terapi."}</p></div></section></div>
  </div>;
}
