import {
  Activity,
  Baby,
  BookOpen,
  Calculator,
  ClipboardList,
  FlaskConical,
  HeartPulse,
  ListChecks,
  Pill,
  Salad,
  ScanSearch,
  Search,
  ShieldAlert,
  Siren,
  Syringe,
  Timer,
  Utensils,
  Weight,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import { CATALOG_COUNTS } from "@/lib/catalog-counts";
import { EMERGENCY_PATHWAYS } from "@/lib/data/emergency";
import { EMERGENCY_PROTOCOLS } from "@/lib/data/protocols";

export interface NavModule {
  slug: string;
  name: string;
  description: string;
  href: string;
  icon: LucideIcon;
  count: number;
  countLabel: string;
  showInNav?: boolean;
}

export const modules: NavModule[] = [
  {
    slug: "igd-toolkit",
    name: "Toolkit IGD",
    description: "Kumpulan kalkulator dan referensi cepat untuk penanganan pasien di IGD.",
    href: "/igd-toolkit",
    icon: Siren,
    count: 11,
    countLabel: "alat",
  },
  {
    slug: "emergency-dose",
    name: "Kalkulator Dosis IGD",
    description: "Hitung dosis total, laju pompa, dan dosis dari laju infus.",
    href: "/emergency-dose",
    icon: Pill,
    count: 8,
    countLabel: "preset",
    showInNav: false,
  },
  {
    slug: "bilirubin",
    name: "Kalkulator Bilirubin",
    description: "Ambang fototerapi dan transfusi tukar neonatus berdasarkan AAP 2022.",
    href: "/bilirubin",
    icon: Baby,
    count: 1,
    countLabel: "alat",
    showInNav: false,
  },
  {
    slug: "antidotes",
    name: "Toksikologi & Antidot",
    description: "Referensi cepat pajanan toksik dan dosis antidot.",
    href: "/antidotes",
    icon: FlaskConical,
    count: 19,
    countLabel: "antidot",
    showInNav: false,
  },
  {
    slug: "pregnancy-drugs",
    name: "Obat Kehamilan & Menyusui",
    description: "Ringkasan pertimbangan obat pada kehamilan dan laktasi.",
    href: "/pregnancy-drugs",
    icon: HeartPulse,
    count: 51,
    countLabel: "obat",
    showInNav: false,
  },
  {
    slug: "electrolytes",
    name: "Koreksi Elektrolit",
    description: "Koreksi natrium, kalsium, kalium, magnesium, dan defisit air bebas.",
    href: "/electrolytes",
    icon: Activity,
    count: 5,
    countLabel: "alat",
    showInNav: false,
  },
  {
    slug: "ddx",
    name: "Mesin Diagnosis Banding",
    description: "Prioritaskan diagnosis banding berdasarkan temuan klinis terpilih.",
    href: "/ddx",
    icon: Search,
    count: 20,
    countLabel: "diagnosis",
    showInNav: false,
  },
  {
    slug: "scores",
    name: "Skrining & Skor",
    description: "Skor klinis, aturan, dan kriteria diagnosis yang tervalidasi. Semua alat menghitung secara otomatis.",
    href: "/scores",
    icon: ListChecks,
    count: CATALOG_COUNTS.scores,
    countLabel: "alat",
  },
  {
    slug: "calculators",
    name: "Kalkulator Klinis",
    description: "Kalkulator dosis, cairan, ginjal, elektrolit, kardiologi dan tubuh.",
    href: "/calculators",
    icon: Calculator,
    count: CATALOG_COUNTS.calculators,
    countLabel: "kalkulator",
  },
  {
    slug: "indications",
    name: "Indikasi & Kontraindikasi",
    description: "Referensi prosedur terstruktur: indikasi, kontraindikasi, dan tindakan pencegahan.",
    href: "/indications",
    icon: ClipboardList,
    count: CATALOG_COUNTS.indications,
    countLabel: "prosedur",
  },
  {
    slug: "drugs",
    name: "Dosis Obat",
    description: "Dosis dewasa dan anak, konversi sediaan, racikan, serta kalkulator terkait.",
    href: "/drugs",
    icon: Pill,
    count: CATALOG_COUNTS.drugs,
    countLabel: "obat",
  },
  {
    slug: "interactions",
    name: "Interaksi Obat",
    description: "Pemeriksa interaksi obat antar pasangan obat secara berpasangan.",
    href: "/interactions",
    icon: ShieldAlert,
    count: CATALOG_COUNTS.interactions,
    countLabel: "interaksi",
  },
  {
    slug: "guidelines",
    name: "Panduan Klinis",
    description: "Ringkasan tata laksana penyakit terstruktur untuk dipakai di samping tempat tidur.",
    href: "/guidelines",
    icon: BookOpen,
    count: CATALOG_COUNTS.guidelines,
    countLabel: "panduan",
  },
  {
    slug: "emergency",
    name: "Algoritma IGD",
    description: "Alur kegawatan dari triase sampai disposisi, menghubungkan panduan, skor, dan kalkulator yang tersedia.",
    href: "/emergency",
    icon: Siren,
    count: EMERGENCY_PATHWAYS.length,
    countLabel: "alur",
  },
  {
    slug: "timer",
    name: "Timer Protokol",
    description: "Penghitung waktu untuk alur waktu-kritis: code stroke, PCI, trombolisis, sepsis, dan trauma.",
    href: "/timer",
    icon: Timer,
    count: EMERGENCY_PROTOCOLS.length,
    countLabel: "protokol",
  },
  {
    slug: "pediatric-emergency",
    name: "Gawat Darurat Anak",
    description: "Ukuran jalan napas, dosis resusitasi, estimasi berat badan, dan tanda vital pediatri.",
    href: "/pediatric-emergency",
    icon: Baby,
    count: 0,
    countLabel: "",
  },
  {
    slug: "neonatal-resuscitation",
    name: "Resusitasi Neonatus",
    description: "Skema lengkap resusitasi bayi baru lahir saat persalinan.",
    href: "/neonatal-resuscitation",
    icon: Workflow,
    count: 0,
    countLabel: "",
  },
  {
    slug: "ecg-atlas",
    name: "Atlas EKG",
    description: "Pengenalan cepat 43 pola ritme, iskemia, blok, dan perubahan metabolik.",
    href: "/ecg-atlas",
    icon: Activity,
    count: 43,
    countLabel: "pola",
  },
  {
    slug: "ecg-module",
    name: "Modul EKG",
    description: "Kurikulum EKG enam pertemuan dengan rujukan guideline dan jurnal primer.",
    href: "/ecg-module",
    icon: BookOpen,
    count: 6,
    countLabel: "pertemuan",
  },
  {
    slug: "radiology-atlas",
    name: "Imaging",
    description: "Pengenalan cepat 159 pola X-ray, CT, MRI, dan USG.",
    href: "/radiology-atlas",
    icon: ScanSearch,
    count: 159,
    countLabel: "pola",
  },
  {
    slug: "anthropometry",
    name: "Antropometri Anak",
    description: "Standar pertumbuhan WHO: z-score, persentil, dan grafik pertumbuhan.",
    href: "/anthropometry",
    icon: Weight,
    count: 0,
    countLabel: "",
  },
  {
    slug: "development",
    name: "Perkembangan Anak",
    description: "Tonggak perkembangan berdasarkan usia dan tanda bahaya (red flags).",
    href: "/development",
    icon: Baby,
    count: 0,
    countLabel: "",
  },
  {
    slug: "immunization",
    name: "Imunisasi",
    description: "Jadwal imunisasi Indonesia: telah, jatuh tempo, akan datang, dan tertunda.",
    href: "/immunization",
    icon: Syringe,
    count: 0,
    countLabel: "",
  },
  {
    slug: "icd10",
    name: "Kamus ICD-10",
    description: "Pencarian cepat kode ICD-10 dengan istilah Bahasa Indonesia.",
    href: "/icd10",
    icon: Search,
    count: CATALOG_COUNTS.icd10,
    countLabel: "kode",
  },
  {
    slug: "nutrition",
    name: "Database Gizi",
    description: "Komposisi pangan untuk praktik klinis Indonesia.",
    href: "/nutrition",
    icon: Utensils,
    count: CATALOG_COUNTS.foods,
    countLabel: "bahan pangan",
  },
  {
    slug: "meal-planner",
    name: "Perencana Makan",
    description: "Rencana makan terstruktur yang dihitung dari database gizi.",
    href: "/meal-planner",
    icon: Salad,
    count: 0,
    countLabel: "",
  },
  {
    slug: "nutrition-guidance",
    name: "Panduan Gizi Klinis",
    description: "Prinsip gizi per kondisi penyakit dan panduan pemilihan makanan.",
    href: "/nutrition-guidance",
    icon: HeartPulse,
    count: CATALOG_COUNTS.nutritionGuidance,
    countLabel: "kondisi",
  },
  {
    slug: "specialties",
    name: "Spesialisasi",
    description: "Telusuri semua alat klinis menurut spesialisasi.",
    href: "/specialties",
    icon: Workflow,
    count: 0,
    countLabel: "",
  },
];

export const appName = "RFSmed";
